apiVersion: v1
kind: Secret
metadata:
  name: {{ .Chart.Name }}-secret
annotations:
  "helm.sh/hook": pre-install
data:
  username: {{ .Values.db.username | b64enc }}
  password: {{ .Values.db.password | b64enc }}
