Vagrant.configure("2") do |config|
  config.vm.box = "smyasnikov/debian-12-arm64"
  config.vm.hostname = "devops"
  config.vm.provider "vmware_desktop" do |v|
    v.gui = true
    v.memory = "512"
    v.cpus = "1"
    v.linked_clone = false
    v.vmx['displayname'] = 'debian12'
  end
  # config.vm.provision "shell", path: "script.sh"
  config.vm.provision "ansible" do |ansible|
    ansible.playbook = "install.yml"
  end
end
