---
apiVersion: v1
kind: Service
metadata:
   name: frontend-service
   labels:
      app: frontend
spec:
   ports:
   - port: 8081
     targetPort: 8081
   selector:
      name: frontend
   type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  labels:
    app: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      name: frontend
  template:
    metadata:
      labels:
        app: frontend
        name: frontend
    spec:
      containers:
        - name: frontend
          image: mtr.devops.telekom.de/sergei_miasnikov/school:frontend.latest
          ports:
            - containerPort: 8081
      imagePullSecrets:
        - name: regcred
