# Job for building jar files and saving them to artifacts
#
# =======================================Usage:
# include:
#   - project: 'sergei.miasnikov/school-ci'
#     ref: main
#     file:
#       - '/gitlab-ci/build-jar.yml'
# stages:
#   - build

build-jar:
  stage: build
  image: $BUILD_JAR_IMAGE
  before_script:
    - export GRADLE_USER_HOME=$CI_PROJECT_DIR/.gradle
  script:
    - apk add openjdk8
    - cd $CI_PROJECT_DIR/backend
    - echo -e "\e[0Ksection_start:`date +%s`:01_section[collapsed=true]\r\e[0KBuilding Backend"
    - ./gradlew build
    - echo -e "\e[0Ksection_end:`date +%s`:01_section\r\e[0K"
    - cd $CI_PROJECT_DIR/frontend
    - echo -e "\e[0Ksection_start:`date +%s`:02_section[collapsed=true]\r\e[0KBuilding Frontend"
    - ./gradlew jar
    - echo -e "\e[0Ksection_end:`date +%s`:02_section\r\e[0K"
  artifacts:
    paths:
      - "$CI_PROJECT_DIR/backend/build/libs/*.jar"
      - "$CI_PROJECT_DIR/frontend/devschool-front-app-server/build/libs/*.jar"
      - "$CI_PROJECT_DIR/frontend/devschool-front-app-client/build/libs/*.jar"
    when: on_success
    expire_in: 1 hour
  cache:
    key: "$CI_COMMIT_REF_NAME"
    paths:
      - $CI_PROJECT_DIR/.gradle/caches/
      - $CI_PROJECT_DIR/.gradle/wrapper/
      - $CI_PROJECT_DIR/frontend/devschool-front-app-client/node_modules
  rules:
    - if: $CI_COMMIT_BRANCH == "main"
    - if: $CI_COMMIT_TAG =~ /v.*/
